node{
    stage("Checkout"){
        checkout(
            [
                $class: 'GitSCM', 
                branches: [
                    [name: '*/main']
                ], 
                extensions: [], 
                userRemoteConfigs: [
                    [
                        credentialsId: 'github_token', 
                        url: 'https://github.com/byroncz/bootcamp-tf-project.git',
                    ]
                ]
            ]
        )
        sh "ls -la"
    }
}